### ISSUE TITLE
Add Trait screen display issues

### ISSUE THREAD

**Issue by Uzhirian** [Vanishoxyact/custom-lords#2] opened 2020-05-11 10:51 UTC
The add trait screen is appearing behind everything else and the content is all weird.

![AfterClickingAddTraits](https://user-images.githubusercontent.com/65162510/81553844-21066c00-93c9-11ea-8f08-73c1b8ec141e.jpg)
![AddTraitScreen](https://user-images.githubusercontent.com/65162510/81553849-24015c80-93c9-11ea-90d8-a3d8497c5cbe.jpg)

**Comment by Vanishoxyact** [comment] 2020-05-11 10:57
Hmm very strange, please can you upload a log file of this happening? Does it happen every time? An upload of the UIMF log would also be helpful.

**Comment by Uzhirian** [comment] 2020-05-11 11:06
Seems pretty consistent, and i disabled all my other mods to be sure no conflicts too.
These were the logs from the last test. 

[script_log_110520_2047.txt](https://github.com/Vanishoxyact/custom-lords/files/4609157/script_log_110520_2047.txt)
[uimf_log.txt](https://github.com/Vanishoxyact/custom-lords/files/4609158/uimf_log.txt)

**Comment by Vanishoxyact** [comment] 2020-05-11 11:07
Thanks, I've managed to reproduce it. It seems to be related to the greenskin lords. I'll look into it for you.

**Comment by Uzhirian** [comment] 2020-05-11 11:08
Damn Orks! Thanks

**Comment by Uzhirian** [comment] 2020-05-11 11:10
I just launched a new game with another race to check (vampire counts) and yes, it appears OK there.

**Comment by Vanishoxyact** [comment] 2020-05-11 12:02
Found the issue, should be fixed now

**Closed as completed** 2020-05-11 12:18 UTC
